# Tutorial 1: Data and Vocabulary

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/byu-matrix-lab/torchlingo/blob/main/docs/docs/tutorials/01-data-and-vocab.ipynb)

**Reference. About 10 minutes.**

This is the library side of what Lecture 4 does by hand: a parallel corpus as a table, turned
into numbers a model can read. Your Assignment 5 output, two sentence-aligned files, becomes
that table with one call to `parallel_txt_to_dataframe`, which the A8 notebook makes.

By the end you will be able to:

1. load two sentence-aligned files into one table, and say why their line counts must match;
2. explain what a vocabulary is, what its four special tokens are for, and why a word seen only once becomes `<unk>`;
3. read a padded batch, and say what the zeros are.

These serve Lecture 9's outcome *explain the fixed-vocabulary problem*, from the library side.

**Running in Google Colab?** Run the next two cells: the first installs TorchLingo, the second
checks the setup. There is nothing to uncomment, and no GPU is needed: nothing here trains a
model.

<!-- GENERATED:purpose - change the torchlingo metadata, not this cell -->

**TorchLingo tutorial** — offered alongside Lecture 4 (*Data Preparation for MT Training*) and Lecture 9 (*Handling Morphology and Terminology in NMT*). A head start on **A9**.

In [1]:
# Install TorchLingo in Colab. Nothing to uncomment. Pip's "you may need to restart the
# kernel" does not apply to a first install; if the install fails, the import below stops here.
import sys
if "google.colab" in sys.modules:
    %pip install --quiet "torchlingo @ git+https://github.com/byu-matrix-lab/torchlingo@course"
    # pip keeps a TorchLingo already in this session when its version number matches, even if
    # it is older code; this swaps in the course branch's, leaving the dependencies alone.
    %pip install --quiet --force-reinstall --no-deps "torchlingo @ git+https://github.com/byu-matrix-lab/torchlingo@course"
import torchlingo

In [2]:
# Check the setup: the TorchLingo and PyTorch versions and the device
import torch
from torchlingo.colab import setup

env = setup()

TorchLingo 0.2.6 (editable checkout) | PyTorch 2.13.0 | device cpu | not in Colab

In [3]:
# Import TorchLingo modules
from torchlingo.preprocessing import load_data, parallel_txt_to_dataframe
from torchlingo.data_processing import SimpleVocab, NMTDataset
from torchlingo.config import Config, get_default_config
from pathlib import Path

print("✓ Imports successful!")

✓ Imports successful!

## Part 1: Loading Data

Assignment 5 hands in two sentence-aligned text files: line *n* of one translates line *n* of
the other. Here are ten pairs written out as two such files, then read back into one table
with `parallel_txt_to_dataframe`, the call the A8 notebook makes on yours.

In [4]:
english = [
    "Hello friend",
    "Hello neighbor",
    "Old friend",
    "How are you today",
    "Happy birthday",
    "Thank you very much",
    "I love programming",
    "The baby is sleeping",
    "What is your name",
    "Nice to meet you",
]
spanish = [
    "Hola amigo",
    "Hola vecino",
    "Amigo viejo",
    "Cómo estás hoy",
    "Feliz cumpleaños",
    "Muchas gracias",
    "Me encanta programar",
    "El bebé está durmiendo",
    "Cuál es tu nombre",
    "Mucho gusto",
]

# Two sentence-aligned files, the shape of an Assignment 5 submission.
data_dir = Path("data")
data_dir.mkdir(exist_ok=True)
src_file, tgt_file = data_dir / "sample.en.txt", data_dir / "sample.es.txt"
src_file.write_text("\n".join(english) + "\n", encoding="utf-8")
tgt_file.write_text("\n".join(spanish) + "\n", encoding="utf-8")
print(f"Wrote {src_file} and {tgt_file}, {len(english)} lines each")

Wrote data/sample.en.txt and data/sample.es.txt, 10 lines each

In [5]:
# One table from the two files. It raises if their line counts differ, because then they are
# not sentence-aligned and nothing built on them would mean anything.
df = parallel_txt_to_dataframe(src_file, tgt_file)

# Saved as one TSV (tab-separated values), the format the rest of the library reads.
data_path = data_dir / "sample_train.tsv"
df.to_csv(data_path, sep="\t", index=False)
print(f"Saved {len(df)} pairs to {data_path}")
df

Saved 10 pairs to data/sample_train.tsv

                    src                     tgt
0          Hello friend              Hola amigo
1        Hello neighbor             Hola vecino
2            Old friend             Amigo viejo
3     How are you today          Cómo estás hoy
4        Happy birthday        Feliz cumpleaños
5   Thank you very much          Muchas gracias
6    I love programming    Me encanta programar
7  The baby is sleeping  El bebé está durmiendo
8     What is your name       Cuál es tu nombre
9      Nice to meet you             Mucho gusto

In [6]:
# Load it back
loaded_df = load_data(data_path)
print(f"Loaded {len(loaded_df)} rows")
loaded_df.head()

Loaded 10 rows

                 src               tgt
0       Hello friend        Hola amigo
1     Hello neighbor       Hola vecino
2         Old friend       Amigo viejo
3  How are you today    Cómo estás hoy
4     Happy birthday  Feliz cumpleaños

## Part 2: Building Vocabularies

Neural networks work with numbers, not text. A vocabulary maps words to indices and back.

In [7]:
# Create a vocabulary
vocab = SimpleVocab()

# Build from sentences
vocab.build_vocab(df["src"].tolist())

print(f"Vocabulary size: {len(vocab)}")
print(f"\nToken to index mapping:")
for token, idx in list(vocab.token2idx.items())[:10]:
    print(f"  '{token}' → {idx}")

Vocabulary size: 8

Token to index mapping:
  '<pad>' → 0
  '<unk>' → 1
  '<sos>' → 2
  '<eos>' → 3
  'Hello' → 4
  'friend' → 5
  'you' → 6
  'is' → 7

### Special Tokens

Notice the first four tokens are special:

| Token | Index | Purpose |
|-------|-------|------|
| `<pad>` | 0 | Padding for batching |
| `<unk>` | 1 | Unknown words |
| `<sos>` | 2 | Start of sequence |
| `<eos>` | 3 | End of sequence |

In [8]:
# Encode a sentence
sentence = "Hello friend"
indices = vocab.encode(sentence, add_special_tokens=True)

print(f"Original: '{sentence}'")
print(f"Encoded:  {indices}")
print(f"Meaning:  [SOS, 'Hello', 'friend', EOS]")

Original: 'Hello friend'
Encoded:  [2, 4, 5, 3]
Meaning:  [SOS, 'Hello', 'friend', EOS]

In [9]:
# Decode back to text
decoded = vocab.decode(indices, skip_special_tokens=True)
print(f"Decoded: '{decoded}'")

# With special tokens
decoded_with_special = vocab.decode(indices, skip_special_tokens=False)
print(f"With special tokens: '{decoded_with_special}'")

Decoded: 'Hello friend'
With special tokens: '<sos> Hello friend <eos>'

### Handling Unknown Words

In [10]:
# What happens with words not in our vocabulary?
unknown_sentence = "Hello universe"
indices = vocab.encode(unknown_sentence, add_special_tokens=True)

print(f"Original: '{unknown_sentence}'")
print(f"Encoded:  {indices}")
# With special tokens
decoded_with_special = vocab.decode(indices, skip_special_tokens=False)
print(f"With special tokens: '{decoded_with_special}'")

Original: 'Hello universe'
Encoded:  [2, 4, 1, 3]
With special tokens: '<sos> Hello <unk> <eos>'

**This `<unk>` is the problem Lecture 9 is about.** The vocabulary kept only the words it saw
at least twice (`min_freq=2`): of its eight entries, four are the special tokens, so ten
sentences left just four real words. Every other word becomes `<unk>`: a model can read it but
never write the word it replaced. Part 3 shows the same thing on the target side, where *amigo*
is lost: it appears twice, but once as *Amigo*, and the vocabulary counts those as two different
words. On a real corpus the rare words are names, numbers and inflected forms, and there are a
great many of them. Lecture 9 and Assignment 9 replace whole words with subword pieces, so that
an unseen word is spelled out from pieces the model has seen instead of vanishing.

## Part 3: Creating Datasets

The `NMTDataset` class combines data loading and vocabulary building.

In [11]:
# Create dataset (vocabularies built automatically)
dataset = NMTDataset(data_path)

print(f"Dataset size: {len(dataset)} samples")
print(f"Source vocab: {len(dataset.src_vocab)} tokens")
print(f"Target vocab: {len(dataset.tgt_vocab)} tokens")

Dataset size: 10 samples
Source vocab: 8 tokens
Target vocab: 5 tokens

In [12]:
# Access a sample
src_tensor, tgt_tensor = dataset[0]

print(f"Sample 0:")
print(f"  Source sentence: '{dataset.src_sentences[0]}'")
print(f"  Source tensor:   {src_tensor.tolist()}")
print(f"  Target sentence: '{dataset.tgt_sentences[0]}'")
print(f"  Target tensor:   {tgt_tensor.tolist()}")

Sample 0:
  Source sentence: 'Hello friend'
  Source tensor:   [2, 4, 5, 3]
  Target sentence: 'Hola amigo'
  Target tensor:   [2, 4, 1, 3]

In [13]:
# Decode to verify
src_decoded = dataset.src_vocab.decode(src_tensor.tolist(), skip_special_tokens=False)
tgt_decoded = dataset.tgt_vocab.decode(tgt_tensor.tolist(), skip_special_tokens=False)

print(f"Source decoded: '{src_decoded}'")
print(f"Target decoded: '{tgt_decoded}'")

Source decoded: '<sos> Hello friend <eos>'
Target decoded: '<sos> Hola <unk> <eos>'

## Part 4: Batching

Training requires batching multiple samples together. Let's see how padding works.

In [14]:
from torch.utils.data import DataLoader
from torchlingo.data_processing import collate_fn

# Create a data loader. The generator seeds the shuffle, so the batch below is the
# same every time you run this, and so is the padding it shows you.
loader = DataLoader(
    dataset,
    batch_size=4,
    shuffle=True,
    collate_fn=collate_fn,
    generator=torch.Generator().manual_seed(0),
)

# Get one batch
src_batch, tgt_batch = next(iter(loader))

print(f"Batch shapes:")
print(f"  Source: {src_batch.shape}  (batch_size, max_src_len)")
print(f"  Target: {tgt_batch.shape}  (batch_size, max_tgt_len)")

Batch shapes:
  Source: torch.Size([4, 6])  (batch_size, max_src_len)
  Target: torch.Size([4, 6])  (batch_size, max_tgt_len)

In [15]:
# Inspect the batch
print("Source batch (notice padding with 0s):")
for i, seq in enumerate(src_batch):
    print(f"  Sample {i}: {seq.tolist()}")

Source batch (notice padding with 0s):
  Sample 0: [2, 1, 1, 6, 1, 3]
  Sample 1: [2, 1, 1, 7, 1, 3]
  Sample 2: [2, 1, 6, 1, 1, 3]
  Sample 3: [2, 1, 5, 3, 0, 0]

## What's next

[Tutorial 3](03-train-tiny-model.ipynb) shows why a vocabulary like this one must be rebuilt
exactly the same way to reuse a saved model, and what goes wrong when it is not.